### ISSUE TITLE
PCDATA invalid error

### ISSUE THREAD

**Issue by GeneticistHere** [aravind-j/augmentedRCBD#15] opened 2023-05-14 14:04 UTC
I have tried this many time once this was done successfully but later now it is showing the same following error:
report.augmentedRCBD.bulk(bout, file.path("~/Downloads", "agmnt.docx"))
Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html, :
PCDATA invalid Char value 27 [9]

**Comment by aravind-j** [comment] 2023-05-14 18:09
@GeneticistHere Can you kindly provide a [reproducible example ](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-create-one/5219/3) for troubleshooting?

**Comment by GeneticistHere** [comment] 2023-05-16 09:49
Here is my issue please solve this as soon as possible
Thanks,
``` r
library(augmentedRCBD)
#> 
#> --------------------------------------------------------------------------------
#> Welcome to augmentedRCBD version 0.1.5
#> 
#> 
#> # To know how to use this package type:
#>   browseVignettes(package = 'augmentedRCBD')
#>   for the package vignette.
#> 
#> # To know whats new in this version type:
#>   news(package='augmentedRCBD')
#>   for the NEWS file.
#> 
#> # To cite the methods in the package type:
#>   citation(package='augmentedRCBD')
#> 
#> # To suppress this message use:
#>   suppressPackageStartupMessages(library(augmentedRCBD))
#> --------------------------------------------------------------------------------
x=R_sheetv2
#> Error in eval(expr, envir, enclos): object 'R_sheetv2' not found
x$Block=as.factor(x$Block)
#> Error in is.factor(x): object 'x' not found
x$`Number of leaflets per leaf`=as.numeric(x$`Number of leaflets per leaf`)
#> Error in eval(expr, envir, enclos): object 'x' not found
x$`Fresh leaf weight(mg)`<-as.numeric(x$`Fresh leaf weight(mg)`)
#> Error in eval(expr, envir, enclos): object 'x' not found
x$Treatment=as.factor(x$Treatment)
#> Error in is.factor(x): object 'x' not found
str(x)
#> Error in str(x): object 'x' not found
bout <- augmentedRCBD.bulk(data = as.data.frame(x), 
                           block = "Block", 
                           treatment = "Treatment", 
                           traits = c("Number of leaflets per leaf", "Fresh leaf weight(mg)"), 
                           checks = c("Check1", "Check2", "Check3"),
                           alpha=0.05, 
                           describe=TRUE, 
                           freqdist=TRUE, 
                           gva=TRUE, 
                           check.col = c('brown', 'yellow', 'blue'), 
                           consol=T)
#> Error in as.data.frame(x): object 'x' not found
report.augmentedRCBD.bulk(bout, file.path("~/Downloads", "agmnt.docx"))
#> Error in is(aug.bulk, "augmentedRCBD.bulk"): object 'bout' not found
tempdir()
#> [1] "/var/folders/ky/673p2xn14nq4_k5_knrn_tk00000gn/T//RtmpUifw02"
report.augmentedRCBD.bulk(bout, file.path(tempdir(),
                                          "augmentedRCBD bulk output.docx"))
#> Error in is(aug.bulk, "augmentedRCBD.bulk"): object 'bout' not found
```

<sup>Created on 2023-05-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by aravind-j** [comment] 2023-05-16 12:19
This issue is a duplicate of #11 and is fixed already.

The updated version is not yet on CRAN. Please try the analysis again with the development version from Github.

**Closed as completed by aravind-j** 2023-05-16 12:19 UTC
Labels: needreprex

**Comment by GeneticistHere** [comment] 2023-05-16 13:26
Sir I'm an introductory user. Did you mean I should install augmentedRCBD version downloaded from GitHub??
